version: '2'
services:
    foodlogbotadm-postgresql:
        image: postgres:9.6.5
        # volumes:
        #     - ~/volumes/jhipster/foodlogbotadm/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=foodlogbotadm
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
